### PR TITLE
TEAL!

### PR DESCRIPTION
**Pull request by stevenilsen123**

### CODE REVIEW

**Comment by dimitriskprs** [comment]
hey @stevenilsen123 , thanks for the pr, I tested it and everything seems to work fine, but in this extension I try to use colors from the official gnome color palette (https://developer.gnome.org/hig/reference/palette.html) and I can't find this teal color (#01897a) in it, did you get it from a different palette?

**Comment by stevenilsen123** [comment]
Yeah, I got it from the [Material Design pallet](https://materialui.co/colors/). Gnome really needs to add Teal and Cyan to their color pallet...

**Comment by dimitriskprs** [comment]
maybe you're right, but I don't know if it's a good idea to start adding colors outside of the official gnome palette in the extension, I do plan to change some of the already existing colors in the extension, but the new colors are still going to be part of the official gnome palette.

**Comment by stevenilsen123** [comment]
Shame... The Teal looks great!

**Comment by dimitriskprs** [comment]
it does look good indeed, I hope it's officially added to the gnome palette at some point.

**Pull request closed without merging**
