### PR TITLE
Added Images

### PR DESCRIPTION
**Pull request by gkapelakos**
Added a few images to help with understanding what the project is about.

### CODE REVIEW

**Comment by dimitriskprs** [comment]
hey @Its-Juice, nice idea! maybe it would be better to have some photos that showcase the shell theming functionality alongside the photos you added, also it would be a good idea to have different accent colors in every photo too.

**Comment by gkapelakos** [comment]
> 

oh yeah, should've  thought of that. Well I'll get to it then!

**Comment by Its-Juice** [comment]
Done!

**Comment by gkapelakos** [comment]
> hey @Its-Juice, nice idea! maybe it would be better to have some photos that showcase the shell theming functionality alongside the photos you added, also it would be a good idea to have different accent colors in every photo too.

Ότι θα έβρισκα Έλληνα στο github δεν το περίμενα! Τα έστειλα τα αρχεία έτσι όπως τα ήθελες. Ελπίζω να δουλεύουν.

**Comment by dimitriskprs** [comment]
Thank you for the photos, I'll check and merge your Pull Request once I'm back home and have access to my computer. (γενικά είμαστε αρκετοί 'Ελληνες στο github και στο linux community :) )

**Pull request merged**
